-- Call records. raw_transcript and patient_name are stored ENCRYPTED by the application (AES-GCM, see FieldCipher), so
-- the database never holds the readable text; redacted_transcript is what the console shows by default.
CREATE TABLE call_record (
    id                  UUID         PRIMARY KEY,
    started_at          TIMESTAMP    NOT NULL,
    duration_sec        INTEGER      NOT NULL CHECK (duration_sec >= 0),
    agent               VARCHAR(60)  NOT NULL,
    caller_label        VARCHAR(40)  NOT NULL,
    reason              VARCHAR(20)  NOT NULL,
    outcome             VARCHAR(20)  NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    flagged             BOOLEAN      NOT NULL DEFAULT FALSE,
    patient_name_enc    TEXT         NOT NULL,
    raw_transcript_enc  TEXT         NOT NULL,
    redacted_transcript TEXT         NOT NULL,
    phi_summary         VARCHAR(200) NOT NULL DEFAULT ''
);
CREATE INDEX idx_call_started_at ON call_record (started_at DESC);
CREATE INDEX idx_call_status ON call_record (status);

-- Append-only audit trail. The application never updates or deletes rows here.
CREATE TABLE audit_event (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at        TIMESTAMP    NOT NULL,
    actor     VARCHAR(80)  NOT NULL,
    actor_role VARCHAR(20) NOT NULL,
    action    VARCHAR(30)  NOT NULL,
    call_id   UUID,
    detail    VARCHAR(400) NOT NULL DEFAULT ''
);
CREATE INDEX idx_audit_at ON audit_event (at DESC);
CREATE INDEX idx_audit_call ON audit_event (call_id);
